name: Deploy intellistay-backend Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Self-hosted GitHub runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          echo "Building latest Docker image..."
          sudo docker build -t intellistay-backend-image .
      - name: Stop & Remove Existing Container
        run: |
          CONTAINER_ID=$(sudo docker ps -aq --filter "name=intellistay-backend-container")
          if [ ! -z "$CONTAINER_ID" ]; then
            sudo docker stop intellistay-backend-container
            sudo docker rm intellistay-backend-container
          fi
      - name: Run New Container from Latest Image
        run: |
          echo "Running container from latest image..."
          sudo docker run -d --name intellistay-backend-container -p 5000:5000 intellistay-backend-image
      - name: Cleanup Unused Docker Images
        run: |
          echo "Cleaning up old Docker images..."
          sudo docker image prune -af
  nginx:
    runs-on: self-hosted
    needs: deploy

    steps:
      - name: Test and Reload Nginx
        run: |
          echo "Testing nginx configuration..."
          sudo nginx -t && sudo systemctl restart nginx
